import 'package:bannerweb_mobile/services/ismayil/auth_service.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AuthProvider with ChangeNotifier {
  final AuthService _authService = AuthService();
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  User? _user;
  bool _isLoading = false;

  // Local State for Profile Data
  String _firstName = '';
  String _lastName = '';
  String _studentId = '00000000';

  // Getters
  User? get user => _user;
  bool get isLoading => _isLoading;
  bool get isAuthenticated => _user != null;
  String get firstName => _firstName;
  String get lastName => _lastName;
  String get studentId => _studentId;
  String get fullName => "$_firstName $_lastName".trim();

  AuthProvider() {
    _authService.authStateChanges.listen((User? newUser) {
      _user = newUser;
      if (newUser != null) {
        // If user is detected (auto-login), load their data from cache
        _loadUserFromCache();
      } else {
        _clearLocalData();
      }
      notifyListeners();
    });
  }

  // --- LOGIN ---
  Future<String?> login(String email, String password) async {
    _setLoading(true);
    try {
      // 1. Authenticate with Firebase Auth
      User? user = await _authService.signIn(email, password);

      if (user != null) {
        // 2. Fetch details from Firestore ONCE
        DocumentSnapshot doc = await _firestore
            .collection('users')
            .doc(user.uid)
            .get();

        if (doc.exists) {
          final data = doc.data() as Map<String, dynamic>;
          // 3. Save to Local Cache (SharedPreferences)
          await _saveToLocalCache(
            data['firstName'] ?? '',
            data['lastName'] ?? '',
            data['studentId'] ?? '',
          );
        }
      }
      _setLoading(false);
      return null;
    } catch (e) {
      _setLoading(false);
      return e.toString();
    }
  }

  // --- SIGN UP ---
  Future<String?> signUp({
    required String email,
    required String password,
    required String firstName,
    required String lastName,
  }) async {
    _setLoading(true);
    try {
      // 1. Create User in Auth & Firestore (Handled by Service)
      await _authService.signUp(
        email: email,
        password: password,
        firstName: firstName,
        lastName: lastName,
      );

      // 2. Since we just created it, we know the data. Save to cache directly.
      // Note: We need to fetch the ID generated by the service or generate it here.
      // For simplicity, we will re-fetch or assume the service handled it.
      // Ideally, the service should return the generated Student ID.
      // For now, let's do a quick fetch to be safe and ensure we get the random ID.
      final currentUser = FirebaseAuth.instance.currentUser;
      if (currentUser != null) {
        DocumentSnapshot doc = await _firestore
            .collection('users')
            .doc(currentUser.uid)
            .get();
        final data = doc.data() as Map<String, dynamic>;
        await _saveToLocalCache(
          data['firstName'] ?? firstName,
          data['lastName'] ?? lastName,
          data['studentId'] ?? 'Pending',
        );
      }

      _setLoading(false);
      return null;
    } catch (e) {
      _setLoading(false);
      return e.toString();
    }
  }

  Future<void> logout() async {
    await _authService.signOut();
    await _clearLocalData();
  }

  // --- HELPER: Save to SharedPreferences ---
  Future<void> _saveToLocalCache(String fName, String lName, String sId) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('firstName', fName);
    await prefs.setString('lastName', lName);
    await prefs.setString('studentId', sId);

    // Update Memory State
    _firstName = fName;
    _lastName = lName;
    _studentId = sId;
    notifyListeners();
  }

  // --- HELPER: Load from SharedPreferences ---
  Future<void> _loadUserFromCache() async {
    final prefs = await SharedPreferences.getInstance();
    _firstName = prefs.getString('firstName') ?? '';
    _lastName = prefs.getString('lastName') ?? '';
    _studentId = prefs.getString('studentId') ?? '00000000';

    // If cache is empty but user is logged in, try fetching from network
    if (_firstName.isEmpty && _user != null) {
      // Optional: Add logic here to fetch from Firestore if cache is missing
    }
    notifyListeners();
  }

  Future<void> _clearLocalData() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove('firstName');
    await prefs.remove('lastName');
    await prefs.remove('studentId');
    _firstName = '';
    _lastName = '';
    _studentId = '00000000';
    notifyListeners();
  }

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }
}
